# Site settings
title: ASCIIbotics Labs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://asciibotics.org" # the base hostname & protocol for your site
twitter_username: asciibotics

# Build settings
markdown: kramdown